### ISSUE TITLE
Make ink! compilation use a dedicated configuration file

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#384]
Currently configuration an ink! compilation works by configuring the parameters of the root ink! macro call, e.g.:

```rust
#[ink::contract(
    version = "0.1.0",
    types = DefaultEnvTypes,
)]
mod my_contract { ... }
```

While this generally works it is bad to merge configuration of build options with code.
This issue proposes to introduce a new dedicated ink! build configuration file inspired by Cargo's `Cargo.toml`.
To make it easier for people that are already acustomed to `Cargo.toml` we could use the same underlying `.toml` encoding to specify ink! parameters.

So an initial so-called `.ink.toml` could look like the following:

```toml
[contract]
name = "flipper"
version = "2.0.0"
types = "DefaultEnvTypes"
authors = "Parity Core Developers"
```
etc.
