### ISSUE TITLE
Unable to transfer contract balance to another account 

### ISSUE THREAD

**Issue by LaurentTrk** [paritytech/ink#538]
Hi,

The `env.transfer()` seems not doing its job in my environment. The balance is not changed, neither in the contract nor in the destination account.  No exception/panic is raised.

I use it in a Ink contract, with something like :

```rust
let value = self.env().balance();
let _ = self.env().transfer(self.charity_pot, value);
```

**Note :** In the same contract, using the same `charity_pot` account, the  `env.terminate_contract()` is correctly transferring the funds to the given account. 

Please let me know if you need additionnal informations. Thanks for your help !

**Environment**

Using  `nightly-2020-08-23` and `cargo-contract 0.7.0` on Ubuntu 20.04.

```toml
[dependencies]
ink_primitives = { version = "3.0.0-rc1", default-features = false }
ink_metadata = { version = "3.0.0-rc1", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc1", default-features = false }
ink_storage = { version = "3.0.0-rc1", default-features = false }
ink_lang = { version = "3.0.0-rc1", default-features = false }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
scale-info = { version = "0.4", default-features = false, features = ["derive"], optional = true }
```
