### ISSUE TITLE
Building `ink` contract with `parity-scale-codec` with `derive` feature fails

### ISSUE THREAD

**Issue by garrettmaring** [paritytech/ink#889]
**Describe the bug**

Since upgrading to `3.0.0-rc4`, I get an error when compiling my contract.

When compiling `scale` with the `derive` feature, usage with other packages that use `std` fails.

```toml
[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
ink_primitives = { version = "3.0.0-rc4", default-features = false }
ink_metadata = { version = "3.0.0-rc4", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc4", default-features = false }
ink_storage = { version = "3.0.0-rc4", default-features = false }
ink_lang = { version = "3.0.0-rc4", default-features = false }
ink_prelude = { version = "3.0.0-rc4", default-features = false }
sp-std = { version = "3.0.0-rc4", default-features = false }
scale = { package = "parity-scale-codec", version = "2.2", features = ["derive"], default-features = false, optional = true }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }
uuid = { version = "0.8", features = ["serde", "v4"], default-features = false, optional = true }

[dev-dependencies]
serde_json = "1.0"
sp-keyring = "3.0.0"

[lib]
name = "contract"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib"
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std"
]
ink-as-dependency = []
```

**Screenshots**

![Screen Shot 2021-08-07 at 11 56 32 AM](https://user-images.githubusercontent.com/8270120/128611874-bd372a92-1517-4961-82d6-768ef3c3b494.png)

**Additional context**

I am importing and using scale to mark certain items with `Encode`/`Decode` such as for chain extension errors
